/**
 * @file emv_kernel/types.h
 * @brief Core type definitions for EMV Contactless Payment Kernel.
 *
 * Platform-independent types, enums, and macros used across the entire kernel.
 * No external dependencies — compiles on any C99 compiler.
 */

#ifndef EMV_KERNEL_TYPES_H
#define EMV_KERNEL_TYPES_H

/* ------------------------------------------------------------------ */
/*  Basic integer types (C99)                                         */
/* ------------------------------------------------------------------ */
#include <stdint.h>
#include <stddef.h>

/* ------------------------------------------------------------------ */
/*  Compile-time configuration                                        */
/* ------------------------------------------------------------------ */

#ifndef MAX_TLV_ENTRIES
#define MAX_TLV_ENTRIES   48          /**< Max TLV entries per transaction  */
#endif

#ifndef MAX_POOL_SIZE
#define MAX_POOL_SIZE     3072        /**< Bytes in warehouse memory pool   */
#endif

#ifndef MAX_KERNEL_ENTRIES
#define MAX_KERNEL_ENTRIES 16         /**< Max registered kernels           */
#endif

#ifndef MAX_DICT_ITEMS
#define MAX_DICT_ITEMS    64          /**< Max items per kernel dictionary  */
#endif

#ifndef MAX_TAG_DESCRIPTION_LEN
#define MAX_TAG_DESCRIPTION_LEN 40    /**< Max chars in dict_item.desc      */
#endif

/* ------------------------------------------------------------------ */
/*  EMV tag helper macros                                             */
/* ------------------------------------------------------------------ */

/* Combine byte pairs into uint32_t tag number */
#define EMV_TAG(b1)            ((uint32_t)(b1))
#define EMV_TAG2(b1, b2)       (((uint32_t)(b1) << 8) | (uint32_t)(b2))
#define EMV_TAG3(b1, b2, b3)   (((uint32_t)(b1) << 16) | ((uint32_t)(b2) << 8) | (uint32_t)(b3))
#define EMV_TAG4(b1, b2, b3, b4) \
    (((uint32_t)(b1) << 24) | ((uint32_t)(b2) << 16) | ((uint32_t)(b3) << 8) | (uint32_t)(b4))

/* Common EMV tag constants (Book A/B/C v2.x) */
#define TAG_AID                  EMV_TAG2(0x4F, 0x00)
#define TAG_APP_LABEL            EMV_TAG2(0x50, 0x00)
#define TAG_PAN                  EMV_TAG2(0x5A, 0x00)
#define TAG_APP_EXPIRY           EMV_TAG2(0x5F, 0x24)
#define TAG_APP_CURRENCY_CODE    EMV_TAG2(0x5F, 0x2A)
#define TAG_AIP                  EMV_TAG2(0x87, 0x00)
#define TAG_AUC                  EMV_TAG2(0x82, 0x00)
#define TAG_TVR                  EMV_TAG2(0x9F, 0x3A)
#define TAG_TA1                  EMV_TAG2(0x80, 0x00)
#define TAG_TB1                  EMV_TAG2(0x81, 0x00)
#define TAG_TC1                  EMV_TAG2(0x9F, 0x26)
#define TAG_NASP                 EMV_TAG2(0x9F, 0x2B)
#define TAG_ICC_CERT             EMV_TAG3(0x9F, 0x21, 0x00)
#define TAG_DDIC                 EMV_TAG3(0x9F, 0x23, 0x00)
#define TAG_CARD_CRT             EMV_TAG3(0x9F, 0x7E, 0x00)
#define TAG_CRYPTogram           EMV_TAG3(0x9F, 0x27, 0x00)

/* ------------------------------------------------------------------ */
/*  Tag source enum                                                   */
/* ------------------------------------------------------------------ */
typedef enum {
    TAG_SRC_TERMINAL,       /* From POS params or terminal-known value  */
    TAG_SRC_CARD_GPO_RESP,  /* Extracted from GPO response TLV          */
    TAG_SRC_CARD_OTHER,     /* Read from card via other APDU            */
    TAG_SRC_GENERATED,      /* Generated by terminal (TN, random num)   */
    TAG_SRC_CONST,          /* Fixed constant per spec                  */
} tag_source_t;

/* ------------------------------------------------------------------ */
/*  Tag data type enum                                                */
/* ------------------------------------------------------------------ */
typedef enum {
    TAG_TYPE_NUMERIC,     /* BCD-encoded numeric (e.g., amount)     */
    TAG_TYPE_INTEGER,     /* Raw integer (big-endian)               */
    TAG_TYPE_BINARY,      /* Raw bytes, no interpretation           */
    TAG_TYPE_STRING,      /* ASCII string                           */
    TAG_TYPE_AID,         /* AID / DF name                          */
    TAG_TYPE_BITMASK,     /* Bit bitmap (AIP, AUC, TVR, TAR)        */
    TAG_TYPE_DATE,        /* YYYYMMDD packed date                   */
    TAG_TYPE_TIME,        /* HHMMSS packed time                     */
} tag_type_t;

/* ------------------------------------------------------------------ */
/*  TLV entry — one key-value pair in the warehouse                    */
/* ------------------------------------------------------------------ */
typedef struct {
    uint32_t tag;        /* EMV tag number (uint32 key)              */
    uint8_t *value;      /* Pointer into shared pool (zero-copy)     */
    uint16_t len;        /* Value length in bytes                    */
} tlv_entry_t;

/* ------------------------------------------------------------------ */
/*  TLV warehouse — transaction-scoped KV store                       */
/* ------------------------------------------------------------------ */
typedef struct {
    uint8_t  pool[MAX_POOL_SIZE];  /* Flat memory pool for all values   */
    uint16_t pool_used;           /* Current offset cursor in pool     */
    tlv_entry_t entries[MAX_TLV_ENTRIES]; /* Array of tag-value entries*/
    uint8_t count;                /* Number of entries currently stored*/
} tx_warehouse_t;

/* ------------------------------------------------------------------ */
/*  Outcome codes (Book A §6)                                         */
/* ------------------------------------------------------------------ */
typedef enum {
    OUTCOME_APPROVE_ISSUER_AUTH,        /* Issuer authorisation required    */
    OUTCOME_APPROVE_TERMINAL_CONDS,     /* Approve under terminal conditions */
    OUTCOME_DECLINE,                    /* Decline this transaction          */
    OUTCOME_RESTART,                    /* Restart — try again               */
    OUTCOME_ERROR,                      /* Unrecoverable error               */
} outcome_code_t;

/* ------------------------------------------------------------------ */
/*  CVM result                                                        */
/* ------------------------------------------------------------------ */
typedef enum {
    CVM_PASS,             /* CVM check passed                          */
    CVM_FAIL,             /* CVM check failed → decline                */
    CVM_NOT_SUPPORTED,    /* This kernel does not support requested CVM  */
} cvm_result_t;

/* ------------------------------------------------------------------ */
/*  Risk result                                                       */
/* ------------------------------------------------------------------ */
typedef enum {
    RISK_PASS,     /* Risk check passed                    */
    RISK_FAIL,     /* Risk check failed → decline          */
    RISK_FALLBACK, /* Risk issue resolved by fallback e.g. CVM */
} risk_result_t;

/* ------------------------------------------------------------------ */
/*  Risk check categories                                             */
/* ------------------------------------------------------------------ */
typedef enum {
    RISK_CHECK_TRM,     /* Terminal Risk Management               */
    RISK_CHECK_CRM,     /* Card Risk Management                   */
    RISK_CHECK_VEL,     /* Velocity Enforcement                   */
    RISK_CHECK_SDS,     /* Signature Data Set                     */
    RISK_CHECK_CVM,     /* CVM result correlation                 */
    RISK_CHECK_TDOL,    /* TDOL data integrity                    */
} risk_check_type_t;

/* ------------------------------------------------------------------ */
/*  Crypto algorithm identifier                                       */
/* ------------------------------------------------------------------ */
typedef enum {
    CRYPTO_DES  = 0,    /* TDES-CMAC / TDES decrypt               */
    CRYPTO_3DES = 1,    /* Triple DES                             */
    CRYPTO_AES  = 2,    /* AES                                    */
    CRYPTO_RSA  = 3,    /* RSA-PKP verify                         */
} crypto_alg_t;

/* ------------------------------------------------------------------ */
/*  Auth method (post-card-auth)                                      */
/* ------------------------------------------------------------------ */
typedef enum {
    AUTH_NONE  = 0,     /* No card authentication performed        */
    AUTH_SDA   = 1,     /* Static Data Authentication passed       */
    AUTH_ODA   = 2,     /* Dynamic Data Authentication passed      */
} auth_method_t;

/* ------------------------------------------------------------------ */
/*  Helper: platform-independent integer utilities                    */
/* ------------------------------------------------------------------ */

/** Pack two BCD digits into one byte (e.g. 0x9F02 amount encoding). */
static inline uint8_t bcd_encode_byte(uint8_t low, uint8_t high)
{
    return (high << 4) | (low & 0x0Fu);
}

/** Decode a BCD byte to separate tens and units. */
static inline void bcd_decode_byte(uint8_t bcd, uint8_t *tens, uint8_t *units)
{
    if (tens) *tens = (bcd >> 4) & 0x0Fu;
    if (units) *units = bcd & 0x0Fu;
}

/** Convert 2-byte BCD amount field to uint32_t. */
static inline uint32_t bcd_2byte_to_uint(const uint8_t *bcd_buf)
{
    return (uint32_t)bcd_buf[0] * 256u + bcd_buf[1];
}

/** Store a uint32_t as 2-byte BCD. Caller must ensure buf has room for 2 bytes. */
static inline void uint_to_bcd_2byte(uint32_t val, uint8_t *out)
{
    out[0] = bcd_encode_byte((uint8_t)(val % 10), (uint8_t)((val / 10) % 10));
    out[1] = bcd_encode_byte((uint8_t)((val / 100) % 10), (uint8_t)((val / 1000) % 10));
}

/** Convert 6-byte BCD (EMV payment amount format) to uint32_t. */
static inline uint32_t bcd_6byte_to_uint(const uint8_t *bcd_buf)
{
    uint32_t val = 0;
    for (int i = 0; i < 6; i++) {
        val = val * 100u + (uint32_t)bcd_buf[i];
    }
    return val;
}

/** Store a uint32_t as 6-byte BCD (EMV payment amount format). */
static inline void uint_to_bcd_6byte(uint32_t val, uint8_t *out)
{
    for (int i = 5; i >= 0; i--) {
        out[i] = bcd_encode_byte((uint8_t)(val % 10), (uint8_t)((val / 10) % 10));
        val /= 100;
    }
}

/** Convert 2-byte big-endian integer to host order. */
static inline uint16_t be16_to_host(const uint8_t *buf)
{
    return ((uint16_t)buf[0] << 8) | (uint16_t)buf[1];
}

/** Store a 16-bit host-order integer as big-endian bytes. */
static inline void host_to_be16(uint16_t val, uint8_t *buf)
{
    buf[0] = (uint8_t)(val >> 8);
    buf[1] = (uint8_t)val;
}

/** Convert 4-byte big-endian integer to host order. */
static inline uint32_t be32_to_host(const uint8_t *buf)
{
    return ((uint32_t)buf[0] << 24) | ((uint32_t)buf[1] << 16) |
           ((uint32_t)buf[2] << 8)  | (uint32_t)buf[3];
}

/** Store a 32-bit host-order integer as big-endian bytes. */
static inline void host_to_be32(uint32_t val, uint8_t *buf)
{
    buf[0] = (uint8_t)(val >> 24);
    buf[1] = (uint8_t)(val >> 16);
    buf[2] = (uint8_t)(val >> 8);
    buf[3] = (uint8_t)val;
}

/* ------------------------------------------------------------------ */
/*  Forward declarations of plugin structs (defined in plugin/*.h)    */
/* ------------------------------------------------------------------ */
struct cvm_plugin_s;
struct risk_plugin_s;
struct crypto_driver_s;

/* ------------------------------------------------------------------ */
/*  Dictionary item — per-kernel tag definition                       */
/* ------------------------------------------------------------------ */
typedef struct {
    uint32_t tag;                     /* EMV tag number                      */
    tag_source_t source;              /* Where does this tag's value come from */
    tag_type_t type;                  /* Data type (numeric, binary, etc.)    */
    uint8_t min_len;                  /* Minimum byte length                 */
    uint8_t max_len;                  /* Maximum byte length                 */
    uint8_t mandatory : 1;            /* Must be present for kernel run       */
    char description[MAX_TAG_DESCRIPTION_LEN];
} dict_item_t;

/* ------------------------------------------------------------------ */
/*  Kernel config — plugin pointers plus metadata                     */
/* ------------------------------------------------------------------ */
/* kernel_ops_t defined in kernel_interface.h */

typedef struct {
    uint8_t  kernel_id;               /* 3, 4, 5, 6, 7, ...               */
    const dict_item_t *items;         /* Tag dictionary                   */
    uint8_t  item_count;              /* Number of items in dictionary     */
    const struct cvm_plugin_s *cvm_plugin;
    const struct risk_plugin_s *risk_plugin;
    const struct kernel_ops_s *ops;   /* Per-kernel processing hooks       */
} kernel_config_t;

/* ------------------------------------------------------------------ */
/*  Dictionary (convenience wrapper for array-based dicts)            */
/* ------------------------------------------------------------------ */
typedef struct {
    uint8_t  kernel_id;
    const dict_item_t *items;          /* Pointer to tag dictionary   */
    uint8_t  item_count;
    const struct cvm_plugin_s *cvm_plugin;
    const struct risk_plugin_s *risk_plugin;
    const struct kernel_ops_s *ops;    /* Per-kernel processing hooks */
} kernel_dict_t;

#endif /* EMV_KERNEL_TYPES_H */
